CP      = cp

all: root.ja.html post.ja.html antenna.ja.html

root.ja.html: root.ja.html.default
	$(CP) $< $@

post.ja.html: post.ja.html.default
	$(CP) $< $@

antenna.ja.html: antenna.ja.html.default
	$(CP) $< $@
